### PR TITLE
Small updates

### PR DESCRIPTION
**Pull request by back-2-95**
- Added .gitignore for development
- Fix `License "GPL-2.0+" is a deprecated SPDX license identifier, use "GPL-2.0-or-later" instead`
- LICENSE file from https://choosealicense.com/licenses/gpl-2.0/
- Changed `machbarmacher/gdpr-dump` to be loaded via type=package repository
- composer validate passes now

### CODE REVIEW

**Comment by robiningelbrecht** [comment]
@back-2-95 Feel free to add your self as an author to the composer.json file...?

**Comment by back-2-95** [comment]
Ah yes, I can do that.

I'm facing a problem now with PHP versions.

`machbarmacher/gdpr-dump` requires `bomoko/mysql-cnf-parser:0.0.2` which requires `nette/finder:^3.0@dev` which requires PHP 8. 😅

**Comment by robiningelbrecht** [comment]
Maybe we could check the possibility to use https://github.com/ifsnop/mysqldump-php? The repo we are using is forked from that one

**Comment by back-2-95** [comment]
I created a fork https://packagist.org/packages/druidfi/gdpr-mysqldump from machbarmacher/gdpr-dump and changed the dependencies. I also included PRs:

- https://github.com/machbarmacher/gdpr-dump/pull/53
- https://github.com/machbarmacher/gdpr-dump/pull/50

Now I was able to install this with Drupal 8 site.

**Pull request merged**
